[plugins]
foojay = { id = "org.gradle.toolchains.foojay-resolver-convention", version = "1.0.0" }
errorprone = { id = "net.ltgt.errorprone", version = "5.1.1" }
shadow = { id = "com.gradleup.shadow", version = "9.6.1" }
spotless = { id = "com.diffplug.spotless", version = "8.10.0" }

[libraries]
errorprone = "com.google.errorprone:error_prone_core:2.50.0"