name: CI

on: [push, workflow_dispatch]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git / setup
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: java / setup
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: gradle / setup
        uses: gradle/actions/setup-gradle@v6

      - name: gradle / build
        run: ./gradlew build

      - name: gradle / publish
        if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/trunk')
        run: ./gradlew publishAllPublicationsToImperiumExternalRepository
        env:
          ORG_GRADLE_PROJECT_imperiumExternalUsername: ${{ secrets.IMPERIUM_EXTERNAL_USERNAME }}
          ORG_GRADLE_PROJECT_imperiumExternalPassword: ${{ secrets.IMPERIUM_EXTERNAL_PASSWORD }}
